### PR TITLE
greendns: IPv6 support, improved handling of /etc/hosts

### PR DESCRIPTION
**Pull request by temoto**
https://github.com/eventlet/eventlet/issues/8
https://bitbucket.org/eventlet/eventlet/issue/105/name-resolution-needs-to-support-ipv6
https://bitbucket.org/eventlet/eventlet/pull-request/40/improve-asynchronous-ipv6-address

### CODE REVIEW

**Comment by PangHua** [comment]
@temoto Howdy,
Thanks for your great work, and I am asking how's the process of greendns IPv6 support, is there any milestone for it to be released?
Thanks.

**Comment by temoto** [comment]
Thank you for reminder.
I'll try to make v0.17 with IPv6 by 2014-02-20.

**Comment by PangHua** [comment]
Thank you :D

**Comment by seocam** [comment]
Looking forward! :+1:

**Comment by temoto** [comment]
Guys, please, test this https://github.com/eventlet/eventlet/commit/a6ce444265d36fb23361809d40da73caf4864487
Python3 feedback is welcome.

**Comment by seocam** [comment]
That's great! Thanks @temoto!!

**Pull request merged**
