### PR TITLE
New feature: Add zipkin tracing to eventlet

### PR DESCRIPTION
**Pull request by yuichib**
Zipkin is a trend distributed tracing framewrok developed at Twitter.
Such tracing is useful for both developers and operatos to
understand the behavior of complex distributed systems
and find performance bottlenecks.

This patch provides a WSGI application using eventlet
with tracing facility that complies with Zipkin.

Signed-off-by: Yuichi Bando bando.yuichi@lab.ntt.co.jp

### CODE REVIEW

**Comment by hieulq** [comment]
hi, what is the current status of this PR? seems like the committer is not involving anymore, right?

**Comment by shwsun** [comment]
Hi, I am also curious about the status on this feature. What happened to it?

**Comment by temoto** [comment]
I'm sorry it was forgotten, merging after CI check.

**Comment by temoto** [comment]
Merged in 654a271
Apologies for delay.

**Pull request closed without merging**
