### PR TITLE
Add new thread attributes from Python 3.13

### PR DESCRIPTION
**Pull request by hroncok**
Does not fix https://github.com/eventlet/eventlet/issues/964 yet

### CODE REVIEW

**Comment by hroncok** [comment]
The result is:

```
FAILED tests/patcher_test.py::test_threading_condition - AssertionError: timed out
FAILED tests/patcher_test.py::test_threading_join - AssertionError: timed out
FAILED tests/patcher_test.py::test_socketserver_selectors - AssertionError: timed out
FAILED tests/patcher_test.py::test_threading_current - AssertionError: timed out
FAILED tests/patcher_test.py::test_threadpoolexecutor - AssertionError: timed out
FAILED tests/patcher_test.py::test_fork_after_monkey_patch - AssertionError: timed out
======= 6 failed, 607 passed, 122 skipped, 51 warnings in 145.16s (0:02:25) =======
```

But at least the tests run now.

**Comment by 4383** [comment]
Thanks Miro for these changes.
Will review them ASAP

**Review by 4383 — APPROVED** [review]
LGTM

**Comment by 4383** [comment]
Merge is blocked by the fact that this PR is in draft mode.

Concerning the tests, as far as I can see, all our jobs are successful, but I think we have to add Python 3.13 jobs to reflect the initial situation behind this PR.

I can prepare a patch to introduce Python 3.13 jobs like the other jobs [1], else, maybe you may prefer adding it through your PR to avoid waiting for it, let me know if you have a preference?

[1] https://github.com/eventlet/eventlet/blob/master/.github/workflows/test.yaml#L52

**Comment by hroncok** [comment]
Whatever is easier for you.

This is marked as draft because it still doesn't work. If you want gradual improvements committed, I can mark it as ready.

**Comment by 4383** [comment]
Thanks Miro for your feedback.

Let me update the jobs in a parallel PR to keeps topics isolated.

Once my patch will be merged, we could rebase here and continue moving forward.

In parallel, if you find a way to fix the failing tests, then do not hesitate to push a new patch set here, I'd be happy to review your PR again.

**Comment by 4383** [comment]
Python 3.13 jobs => #966

**Comment by 4383** [comment]
Waiting for https://github.com/python-greenlet/greenlet/pull/396 to continue with Python 3.13 support and with your patch.

**Comment by hroncok** [comment]
> Waiting for [python-greenlet/greenlet#396](https://github.com/python-greenlet/greenlet/pull/396) to continue with Python 3.13 support and with your patch.

Waiting for it to be merged and released? Perhaps there is a way to install greenlet from that PR... something like `pip install https://github.com/vstinner/greenlet/archive/refs/heads/py313.zip`

**Comment by 4383** [comment]
Thanks Miro, we mostly wait for #966, but if greenlet is also broken on Python 3.13, as Eventlet is based on greenlet that's a blocker for our internal Python 3.13 support

**Comment by AdamWill** [comment]
So I tried this locally (I'm also a Fedora packager helping with the Python 3.13 rebuild), and one thing I note is that among all the messages from the failures are four greenlet errors:
```
stdout_seq = [b'Traceback (most recent call last):\n', b'  File "/builddir/build/BUILD/python-eventlet-0.36.1-build/eventlet-0.36.1... in _do_acquire\n    waiter.switch()\n    ~~~~~~~~~~~~~^^\ngreenlet.error: cannot switch to a different thread\n', b'']
greenlet.error: cannot switch to a different thread
stdout_seq = [b'Traceback (most recent call last):\n', b'  File "/builddir/build/BUILD/python-eventlet-0.36.1-build/eventlet-0.36.1...do_acquire\n    waiter.switch()\n    ~~~~~~~~~~~~~^^\n', b'greenlet.error: cannot switch to a different thread\n', b'']
greenlet.error: cannot switch to a different thread
stdout_seq = [b'Traceback (most recent call last):\n', b'  File "/builddir/build/BUILD/python-eventlet-0.36.1-build/eventlet-0.36.1...do_acquire\n    waiter.switch()\n    ~~~~~~~~~~~~~^^\n', b'greenlet.error: cannot switch to a different thread\n', b'']
greenlet.error: cannot switch to a different thread
stdout_seq = [b'Traceback (most recent call last):\n', b'  File "/builddir/build/BUILD/python-eventlet-0.36.1-build/eventlet-0.36.1...do_acquire\n    waiter.switch()\n    ~~~~~~~~~~~~~^^\n', b'greenlet.error: cannot switch to a different thread\n', b'']
greenlet.error: cannot switch to a different thread
```
that error is documented at https://github.com/python-greenlet/greenlet/blob/937f150e07823ee03344aeeb5111c0bb371a831d/docs/python_threads.rst - "Greenlets can be combined with Python threads; in this case, each thread contains an independent "main" greenlet with a tree of sub-greenlets. It is not possible to mix or switch between greenlets belonging to different threads." So...that makes me wonder, maybe the greenlet patch we applied downstream - https://github.com/python-greenlet/greenlet/pull/396 - was sufficient for greenlet to pass its tests, but wasn't entirely correct? or is eventlet really doing something wrong with greenlet here...

**Comment by 4383** [comment]
> So I tried this locally (I'm also a Fedora packager helping with the Python 3.13 rebuild), and one thing I note is that among all the messages from the failures are four greenlet errors:
> 

Please, can you share we us the names of the tests which triggered these greenlet error?
I agree that this is symptomatic of using a native python thread within a greenlet context... which is something not supported by greenlet.

> ```
> 
> that error is documented at https://github.com/python-greenlet/greenlet/blob/937f150e07823ee03344aeeb5111c0bb371a831d/docs/python_threads.rst - "Greenlets can be combined with Python threads; in this case, each thread contains an independent "main" greenlet with a tree of sub-greenlets. It is not possible to mix or switch between greenlets belonging to different threads." So...that makes me wonder, maybe the greenlet patch we applied downstream - [python-greenlet/greenlet#396](https://github.com/python-greenlet/greenlet/pull/396) - was sufficient for greenlet to pass its tests, but wasn't entirely correct? or is eventlet really doing something wrong with greenlet here...

Yes maybe some tests are not correct, not yet sure...

**Pull request closed without merging**
