### PR TITLE
Add get_server_info to db_pool.py

### PR DESCRIPTION
**Pull request by ernstp**
Django uses this for example.

### CODE REVIEW

**Review by 4383 — APPROVED** [review]
Hello,

Is this patch still relevant?
AFAICS these changes make sense.

**Comment by ernstp** [comment]
Wow, that was a long time ago! :-D

I guess step one is to rebase this! Feel free to do that and push and so on if you have time... I might have time to look at it in the weekend otherwise.

**Comment by 4383** [comment]
hm... something went wrong during your rebase. All tests are failing and your addition does not seems in the right place in the code like before. Please check

**Comment by ernstp** [comment]
I guess it should be like this now.. ?

**Comment by 4383** [comment]
Looks better, thanks

**Pull request merged**
