### PR TITLE
Modified pyopenssl example using evenlet

### PR DESCRIPTION
**Pull request by Aayush-Kasurde**
Fixes issue #79 

Signed-off-by: Aayush Kasurde aayush.kasurde@gmail.com

### CODE REVIEW

**Comment by Aayush-Kasurde** [comment]
Can anyone point me, why this build failed ?

**Comment by temoto** [comment]
Eventlet tests have CPU usage counter and sometimes it exceeds allowed limit when running on Travis, maybe it's connected to Travis machines load. Bottom line: if you are not sure that Travis failure is connected to your patch, don't worry about it.

**Comment by Aayush-Kasurde** [comment]
This change is related to documentation, so I am not sure why Travis failed.

**Comment by temoto** [comment]
Github contains webhook to ping Travis to run all available tests on any commit. Sad fact is that right now Travis tests may fail for CPU usage check without actual problem in code.

Sometimes I restart failed tests to enjoy green builds and sometimes I just ignore them, knowing that there is no problem. I also make a green build before releasing new version. But also I see how it distracts and bothers people who care about green builds in their pull requests, so that's something I work on, but it's not a priority.

**Comment by temoto** [comment]
Merged in master 0f81f03bf6913f1c7b662fa4442c42973666c0af
Thank you.

**Pull request closed without merging**
