### PR TITLE
Python 3.13 Support

### PR DESCRIPTION
**Pull request by stefanor**
Following on from #966, implement the Python 3.13 `start_joinable_thread` API using greenthreads.

We cut some corners, of course:
* We aren't maintaining a table of green thread idents to threads, so we can't wait for all threads on shutdown.
* Our `_make_thread_handle()` can only make a handle for the current thread (as we don't have a way to look up green threads by ident). This seems to be good enough.
* `.join()` on a non-GreenThread (e.g. the main thread) just returns immediately.

### CODE REVIEW

**Comment by 4383** [comment]
Thank you @stefanor

**Comment by stefanor** [comment]
Force-pushed. No code changes, just broke out an unrelated change and labelled the commits a bit better.

**Comment by 4383** [comment]
Asyncio jobs are still failing under Python 3.13

**Comment by stefanor** [comment]
> Asyncio jobs are still failing under Python 3.13

Interesting that those pass on CI for < 3.13. That particular test fails on all Python versions I tested, locally.

**Comment by 4383** [comment]
@stefanor is the following error is the same that the one you spoke about in your previous comment?

```
 ____________________ TestHttpd.test_017_ssl_zeroreturnerror ____________________

self = <tests.wsgi_test.TestHttpd testMethod=test_017_ssl_zeroreturnerror>

    @tests.skip_if_no_ssl
    def test_017_ssl_zeroreturnerror(self):
    
        def server(sock, site, log):
            try:
                serv = wsgi.Server(sock, sock.getsockname(), site, log)
                client_socket, addr = sock.accept()
                serv.process_request([addr, client_socket, wsgi.STATE_IDLE])
                return True
            except (ssl.SSLZeroReturnError, ssl.SSLEOFError):
                # Can't write a response to a closed TLS session
                return True
            except OSError:
                if sys.version_info[:2] == (3, 7):
                    return True
                else:
                    traceback.print_exc()
                    return False
            except Exception:
                traceback.print_exc()
                return False
    
        def wsgi_app(environ, start_response):
            start_response('200 OK', [])
            return [environ['wsgi.input'].read()]
    
        certificate_file = os.path.join(os.path.dirname(__file__), 'test_server.crt')
        private_key_file = os.path.join(os.path.dirname(__file__), 'test_server.key')
    
        sock = eventlet.wrap_ssl(
            eventlet.listen(('localhost', 0)),
            certfile=certificate_file, keyfile=private_key_file,
            server_side=True)
        server_coro = eventlet.spawn(server, sock, wsgi_app, self.logfile)
    
        client = eventlet.connect(('localhost', sock.getsockname()[1]))
        client = eventlet.wrap_ssl(client)
        client.write(b'X')  # non-empty payload so that SSL handshake occurs
        greenio.shutdown_safe(client)
        client.close()
    
        success = server_coro.wait()
>       assert success
E       assert False

tests/wsgi_test.py:613: AssertionError
----------------------------- Captured stderr call -----------------------------
127.0.0.1 - - [14/Nov/2024 11:58:19] code 400, message Bad request syntax ('X')
127.0.0.1 - - [14/Nov/2024 11:58:19] "X" 400 -
Traceback (most recent call last):
  File "/Users/runner/work/eventlet/eventlet/tests/wsgi_test.py", line 578, in server
    serv.process_request([addr, client_socket, wsgi.STATE_IDLE])
  File "/Users/runner/work/eventlet/eventlet/eventlet/wsgi.py", line 905, in process_request
    proto.__init__(conn_state, self)
  File "/Users/runner/work/eventlet/eventlet/eventlet/wsgi.py", line 360, in __init__
    self.finish()
  File "/Users/runner/work/eventlet/eventlet/eventlet/wsgi.py", line 819, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 825, in finish
    self.wfile.close()
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py", line 738, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/eventlet/eventlet/eventlet/green/ssl.py", line 206, in send
    return self._call_trampolining(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/eventlet/eventlet/eventlet/green/ssl.py", line 166, in _call_trampolining
    return func(*a, **kw)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1179, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SYS] unknown error (_ssl.c:2417)
```

It seems to me that that's not the same job that fail now.
Only the macos jobs are failing (within an asyncio context).

**Comment by stefanor** [comment]
> @stefanor is the following error is the same that the one you spoke about in your previous comment?

No, that's new to me. Sorry, I can't investigate the MacOS failures.

**Comment by 4383** [comment]
Make me wonder if we should shrink and restrict the official support to linux likes.
Eventlet is close from retirement and accounting our lake of resources I do not see reasons to spend time on "exotic" OS.
By exotic OS that are not significants https://pypistats.org/packages/eventlet
Darwin/Mac represent 0.44% of share among all Eventlet the downloads... I'd at least suggest to move the Mac job as non-voting jobs, and if people want to take care of Mac they are still free to propose patches.

**Comment by 4383** [comment]
Let me ping my CPython colleagues to get their expertises. 

@vstinner @hroncok do you mind to double check this patch to see if it is aligned with CPython 3.13. The current version LGTM, however, I'm far from being an expert of stdlib monkey patching so I might potentially miss some aspects. Feel free to ignore the MacOS problem and to focus only on the semantic behind this pull request, aka, the support of Python 3.13.

Thanks in advance.

**Review by 4383 — APPROVED** [review]
LGTM but need a double check from someone else than me with more expertise about Python 3.13

**Comment by 4383** [comment]
Well, in the end MacOS jobs are not blocking

**Comment by hroncok** [comment]
Unfortunately, I don't have the capacity to look over this. Sorry

**Comment by 4383** [comment]
@hroncok no problem, thank you

**Review by vstinner — APPROVED** [review]
Overall LGTM. I'm not an eventlet developer. If tests pass, I guess that it's good :-)

**Comment by 4383** [comment]
@vstinner thanks Victor

**Pull request merged**
