### PR TITLE
fix client certificates

### PR DESCRIPTION
**Pull request by plockaby**
This is for #567.

### CODE REVIEW

**Comment by plockaby** [comment]
Is there anything I can do to get this PR merged?

**Comment by temoto** [comment]
@plockaby hi I'm so sorry whole year passed. Do you think you could write a test for this?

**Comment by plockaby** [comment]
Yes, it has been more than a year. Because I couldn't get this fixed I just stopped using eventlet so I'm not able to write a test to fix this bug.

**Comment by temoto** [comment]
@plockaby I understand, sorry. I will write a test and merge then.

**Review by jesper-newzoo — APPROVED** [review]

**Comment by temoto** [comment]
Moved to https://github.com/eventlet/eventlet/pull/705  because I can't add commit with test to deleted repo.

**Pull request closed without merging**
