### PR TITLE
Provide green http without undesired side effects

### PR DESCRIPTION
**Pull request by jstasiak**
The Eventlet patcher and the way we were patching multi-level http
package don't work well[1][2]. I spent a lot of time trying to make it
work but in the end every solution I came up with was breaking something
else and made the patching and providing green http even more
complicated - I wouldn't envy anyone having to debug it in the future.

After a lot of thinking I decided having our own copy of http with the
necessary modifications applied seems like the most straightforward and
the most reliable solution, even considering its downsides (we need to
keep it up to date ourselves and the API won't 100 % match the regular
http module API on older Python 3 versions as our bundled version is the
most recent one and has bug fixes and extra features implemented).

The code introduces by this commit comes from the following Python
commit (development branch):

```
commit 6251d66ba9a692d3adf5d2e6818b29ac44130787
Author: Xavier de Gaye <xdegaye@users.sourceforge.net>
Date:   2016-06-15 11:35:29 +0200

    Issue #26862: SYS_getdents64 does not need to be defined on android
    API 21.
```

Changes to the originl http package code involve:

* Removing unnecessary import(s)
* Replacing some regular imports with eventlet.green imports
* Replacing fullmatch()[3] usage with match() so we stay Python 3.3
  compatible

I left urllib.parse imports intact as nothing there performs IO.

[1] https://github.com/getsentry/raven-python/issues/703
[2] https://github.com/eventlet/eventlet/issues/316
[3] https://docs.python.org/3/library/re.html#re.fullmatch

This addresses https://github.com/getsentry/raven-python/issues/703 fully and https://github.com/eventlet/eventlet/issues/316 partially.

@temoto Can you have a look? This addresses an issue that blocks us from porting one of our applications to Python 3.

### CODE REVIEW

**Comment by jstasiak** [comment]
There are some minor issues with the patch but I'm sorting them out.

**Comment by jstasiak** [comment]
I think that's it, I just tested this patch against one of our applications and it works!

**Comment by jstasiak** [comment]
@temoto Do you have any strong feelings either way here? I'm inclined to merge this sooner rather than later unless there are reasons not to.

**Comment by jstasiak** [comment]
Just pushed to master as c93279086c21b9f838e1f9c9b232d60317fcfc71, if there are any concerns about this please let me know.

**Comment by temoto** [comment]
LGTM. Hooray to more stdlib code inside ours.

**Pull request closed without merging**
