### PR TITLE
[green.zmq] Fix args/kwargs of socket's methods

### PR DESCRIPTION
**Pull request by gdavoian**
Make socket's methods consistent with official pyzmq library and its documentation.

### CODE REVIEW

**Comment by ozamiatin** [comment]
Thanks, gdavoian! My bad with arguments ...

**Comment by mchwalisz** [comment]
this should fix #376

**Comment by temoto** [comment]
Thanks for reminding.

@gdavoian I hope you don't mind including few changes to zmq_test into your patch. Review here ceff431231a2821682b029deb55a11a4b9afaf6f

**Comment by gdavoian** [comment]
I am ok, feel free to fix the patch. I don't mind.

**Comment by temoto** [comment]
Merged in master ceff431231a2821682b029deb55a11a4b9afaf6f will be published in next release v0.21

Have a nice day.

**Pull request closed without merging**
