### PR TITLE
Fix AttributeError GreenPipe._rbuf

### PR DESCRIPTION
**Pull request by rutube**
In Python3 GreenPipe is a child of socket.SocketIO class, that doesn't have _rbuf attribute. That is why any attempt to use tell or seek on it is raising AttributeError.

### CODE REVIEW

**Comment by jstasiak** [comment]
@temoto: This is still an issue

@rutube: I'm in process of changing that code extensively so it uses buffering and decoding/encoding infrastructure from Python 3 io module and we won't need this workaround but thank you for the contribution, I'll leave this open until it's fixed.

**Comment by temoto** [comment]
@jstasiak will you finish the change before v0.17 at 2014-02-20? By the way, thanks for merging other pull requests.

**Comment by jstasiak** [comment]
No problem. Yeah I should have some test-passing code by then.

**Comment by jstasiak** [comment]
This is fixed in master so I'll close.

**Pull request closed without merging**
