### PR TITLE
Candidate fix for #526 (unsupported _context param)

### LINKED ISSUE #526: python 3.7 - wrap_socket() got  an unexpected keyword argument '_context'
I develop an app with flask-socket.io and because of the new merge of #506 i thought i can upgrade the python version to 3.7. I used eventlet.monkey_patch.  Not sure if it is an issue of eventlet, but on connection i get following Trace:

```
message handler error
Traceback (most recent call last):
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/engineio/server.py", line 411, in _trigger_event
    return self.handlers[event](*args)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/socketio/server.py", line 518, in _handle_eio_message
    self._handle_connect(sid, pkt.namespace)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/socketio/server.py", line 421, in _handle_connect
    self.environ[sid]) is False:
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/socketio/server.py", line 495, in _trigger_event
    event, *args)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/flask_socketio/namespace.py", line 26, in trigger_event
    *args)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/flask_socketio/__init__.py", line 632, in _handle_event
    ret = handler()
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/server/auth/__init__.py", line 10, in wrapped
    if not current_user.is_authenticated:
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/flask_login/login_manager.py", line 355, in _load_user
    return self._load_from_request(request)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/flask_login/login_manager.py", line 412, in _load_from_request
    user = self.request_callback(request)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/geocatch_persistence/login_manager.py", line 35, in load_user_from_request
    return user or validate_token(token)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/geocatch_persistence/login_manager.py", line 69, in validate_token
    current_app.config.get("GOOGLE_CLIENT_ID"))  # type: dict
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/google/oauth2/id_token.py", line 141, in verify_oauth2_token
    certs_url=_GOOGLE_OAUTH2_CERTS_URL)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/google/oauth2/id_token.py", line 120, in verify_token
    certs = _fetch_certs(request, certs_url)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/google/oauth2/id_token.py", line 94, in _fetch_certs
    response = request(certs_url, method='GET')
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 120, in __call__
    **kwargs)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/eventlet/green/ssl.py", line 426, in wrap_socket
    return GreenSSLSocket(sock, *a, _context=self, **kw)
  File "/home/nexodaru/Workspace/Geocatch_2.0/code/socket.io/venv/lib/python3.7/site-packages/eventlet/green/ssl.py", line 79, in __init__
    *args, **kw
TypeError: wrap_socket() got an unexpected keyword argument '_context'

```

### PR DESCRIPTION
**Pull request by nat-goodspeed**
Fixes #526

### CODE REVIEW

**Comment by nat-goodspeed** [comment]
The first step is to verify that we already have at least one test that demonstrates this issue with Python 3.7.3. If not, such a test must be added.

That's why the initial commit for this PR is only a comment.

**Comment by nat-goodspeed** [comment]
Well. Travis's python37 is 3.7.1, which doesn't drive the problem.

**Comment by nat-goodspeed** [comment]
Okay, so [I specified Python 3.7.3](https://github.com/eventlet/eventlet/pull/565/commits/e9cc890429fc4b96b7d913134280a08d3259cfa5) for Travis testing -- and [all existing tests passed](https://travis-ci.org/eventlet/eventlet/builds/528173659?utm_source=github_status&utm_medium=notification)!

Yet I can reproduce #526 merely by attempting a simple `requests` HTTPS connection from my local machine with Python 3.7.3 and `eventlet.monkey_patch(socket=True)`.

Means (a) there's some other factor involved than specifically Python 3.7.3 or (b) we don't yet have a test that drives this problem. I'll pursue (b) for now.

**Comment by rahulverma** [comment]
Any update on this? python3.7.4 with celery, eventlet and request just fails.

**Comment by nat-goodspeed** [comment]
Odd. The new test script is currently failing to [import requests](https://travis-ci.org/eventlet/eventlet/jobs/587562973#L1446) -- despite the successful [pip install requests](https://travis-ci.org/eventlet/eventlet/jobs/587562973#L323) earlier in the same run.
I assume that failure is typical of them all.

**Comment by nat-goodspeed** [comment]
Yes: I just clicked through all the reported failures. Same thing: missing `requests` module.

**Comment by nat-goodspeed** [comment]
Good news: we finally have a test that drives the problem!
Bad news: I inadvertently broke another test. Working on that.

**Comment by nat-goodspeed** [comment]
Okay! On this branch we have a single new test that drives the reported problem.

**Comment by paunovic** [comment]
Hi guys. Any updates on this?

**Comment by itamarst** [comment]
Looks like #526 was closed some other way.

**Pull request closed without merging**
