### PR TITLE
Use external dependencies for six, monotonic, dnspython. 

### PR DESCRIPTION
**Pull request by nat-goodspeed**
Remove the snapshots of these packages embedded in `eventlet/support`; instead use `setup.py`'s `install_requires` and `dependency_links` features to fetch them into the top-level package namespace. Also remove `pull-dnspython` and `pull-monotonic` from the `bin` directory.

Because embedded snapshots are inherently version-locked, these dependencies are likewise version-locked.

As of 2018-05-01, `dnspython` version 1.16.0 that was embedded in `eventlet/support` is not yet available from [PyPI](https://pypi.org/project/dnspython/). `bin/pull-dnspython` referenced [a specific commit in the upstream github.com repository](https://github.com/rthalley/dnspython/commit/22e9de1d7957e558ea8f89f24e402cbbc8d50646); the same commit ID in the same repository is referenced in the dependency_links URL. However, it seems that this mechanism requires the user to specify pip's `--process-dependency-links`switch.

Finally, remove `eventlet`'s explicit references to `eventlet.support` when importing `six`, `monotonic` and `dns`.

### CODE REVIEW

**Comment by temoto** [comment]
Does this help with your freezer?

**Comment by nat-goodspeed** [comment]
This is an alternative to PR #482, one whose changes are constrained to the way `eventlet` consumes `six`, `monotonic` and `dnspython` rather than 482's pervasive patches to `dnspython` itself.

I confirm that these changes allow PyInstaller to successfully package my application that consumes eventlet, with this `hook-eventlet.support.greendns.py` file in a PyInstaller `--additional-hooks-dir` directory:

    # PyInstaller hook for dynamic import of dnspython

    from PyInstaller.utils.hooks import collect_submodules
    hiddenimports = collect_submodules('dns')

Please pardon my leaning on your CI to verify the self-consistency of the `eventlet` changes.

**Comment by nat-goodspeed** [comment]
The CI failures are because, with the dependency on a `dnspython` version that is not yet available from PyPI, it is essential to use the `setup()` `dependency_links` feature to specify the github.com URL. But `dependency_links` isn't transparent: you must specify pip's `--process-dependency-links` switch.

I [tried to add that switch](https://github.com/eventlet/eventlet/pull/486/commits/5212f6f41a1ff576d348b660633189e74b86853f), but clearly I don't understand the requisite CI magic well enough to do it correctly. Would you please make the correct fix?

**Comment by temoto** [comment]
We also have no power to force everybody to use this flag, so don't worry about it. Should either specify lesser version or wait for their release.

**Comment by temoto** [comment]
This must remain fixed for dnspython https://github.com/eventlet/eventlet/issues/427 

tests/isolated/socket_resolve_green.py should catch it.

**Comment by nat-goodspeed** [comment]
> This must remain fixed for dnspython #427
> tests/isolated/socket_resolve_green.py should catch it.

Sergey, I don't quite understand. Are you telling me to revert to requiring `dnspython >= 1.16.0`?

**Comment by temoto** [comment]
Now that tests passed no. I pointed to last available dnspython commit at that time but it turns out it was included in 15.

**Comment by nat-goodspeed** [comment]
Given that `dnspython` 1.15.0 addresses the problem, should I remove [the `dependency_links` entry in `setup.py`](https://github.com/eventlet/eventlet/pull/486/files#diff-2eeaed663bd0d25b7e608891384b7298) and [the `--process-dependency-links` switch from `.travis.yml`](https://github.com/eventlet/eventlet/pull/486/files#diff-354f30a63fb0907d4ad57269548329e3)?

**Comment by temoto** [comment]
Sure Nat. Thank you.

**Comment by nat-goodspeed** [comment]
I think this one is ready too. Not poking, just being explicit.

**Comment by temoto** [comment]
I'm excited. Thanks Nat.

**Pull request merged**
